### ISSUE TITLE
Linebreaks

### ISSUE THREAD

**Issue by MichiBaum** [DaniloMurer/DaniloMurer#1]
You may want to add linebreaks br's like in html after:

- Your twitter link
- Your github stats

![image](https://user-images.githubusercontent.com/36712219/92310544-d8924000-efaf-11ea-8e99-8258f0bde0be.png)

**Comment by DaniloMurer** [comment]
@MichiBaum think i fixed it right now? Maybe you could review it and give me feedback on that, because I didn't really get your point there. But the `<br>` are now added in the README.
